version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: questify
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: QpPass2023
      POSTGRES_DB: questy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  # adminer: # Optional: A database UI for management
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: