name: CI for Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'

      - name: Build the project
        run: go build ./...

      - name: Run unit tests
        run: go test -v ./tests/...

      - name: Check code quality
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
          

      - name: Check commit message format
        run: |
          ./scripts/commit-msg-hook.sh